CREATE TABLE public.tahsilatlar (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    firma_id INT NOT NULL,
    tahsilat_tarihi DATE NOT NULL,
    odeme_kanali TEXT NOT NULL,
    acente_payi NUMERIC(10, 2) DEFAULT 0 NOT NULL,
    ofis_payi NUMERIC(10, 2) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    CONSTRAINT tahsilatlar_pkey PRIMARY KEY (id),
    CONSTRAINT tahsilatlar_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES public.firmalar(id) ON DELETE CASCADE
);

ALTER TABLE public.tahsilatlar ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON public.tahsilatlar FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users" ON public.tahsilatlar FOR INSERT WITH CHECK (auth.role() = 'admin' OR auth.role() = 'standart');
CREATE POLICY "Enable update for authenticated users" ON public.tahsilatlar FOR UPDATE USING (auth.role() = 'admin' OR auth.role() = 'standart');
CREATE POLICY "Enable delete for authenticated users" ON public.tahsilatlar FOR DELETE USING (auth.role() = 'admin' OR auth.role() = 'standart');

COMMENT ON TABLE public.tahsilatlar IS 'Firmalardan yapılan tahsilatları (ödeme, acente ve ofis payları) tutar.';
